with-expecter: true
packages:
  dvnetman/pkg/openapi:
    # place your package-specific config here
    config:
      all: true
      inpackage: true
      dir: pkg/openapi
      filename: "mock_{{.InterfaceName}}_test.go"
  dvnetman/pkg/mongo/adapt:
    config:
      dir: pkg/mongo/adapt/mock
      all: true

resolve-type-alias: False
issue-845-fix: True
