// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeviceType,
  DeviceTypeSearchBody,
  DeviceTypeSearchResults,
} from '../models/index';
import {
    DeviceTypeFromJSON,
    DeviceTypeToJSON,
    DeviceTypeSearchBodyFromJSON,
    DeviceTypeSearchBodyToJSON,
    DeviceTypeSearchResultsFromJSON,
    DeviceTypeSearchResultsToJSON,
} from '../models/index';

export interface CreateDeviceTypeRequest {
    deviceType: Omit<DeviceType, 'created'|'id'|'updated'>;
}

export interface DeleteDeviceTypeRequest {
    id: string;
}

export interface GetDeviceTypeRequest {
    id: string;
    ifNoneMatch?: string;
    ifModifiedSince?: Date;
}

export interface ListDeviceTypesRequest {
    page?: number;
    perPage?: number;
    sort?: string;
    deviceTypeSearchBody?: DeviceTypeSearchBody;
}

export interface UpdateDeviceTypeRequest {
    id: string;
    deviceType: Omit<DeviceType, 'created'|'id'|'updated'>;
}

/**
 * DeviceTypeApi - interface
 * 
 * @export
 * @interface DeviceTypeApiInterface
 */
export interface DeviceTypeApiInterface {
    /**
     * 
     * @param {DeviceType} deviceType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceTypeApiInterface
     */
    createDeviceTypeRaw(requestParameters: CreateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceType>>;

    /**
     */
    createDeviceType(requestParameters: CreateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceType>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceTypeApiInterface
     */
    deleteDeviceTypeRaw(requestParameters: DeleteDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteDeviceType(requestParameters: DeleteDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {string} [ifNoneMatch] 
     * @param {Date} [ifModifiedSince] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceTypeApiInterface
     */
    getDeviceTypeRaw(requestParameters: GetDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceType>>;

    /**
     */
    getDeviceType(requestParameters: GetDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceType>;

    /**
     * 
     * @param {number} [page] Page number
     * @param {number} [perPage] Number of items per page
     * @param {string} [sort] Sort order
     * @param {DeviceTypeSearchBody} [deviceTypeSearchBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceTypeApiInterface
     */
    listDeviceTypesRaw(requestParameters: ListDeviceTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceTypeSearchResults>>;

    /**
     */
    listDeviceTypes(requestParameters: ListDeviceTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceTypeSearchResults>;

    /**
     * 
     * @param {string} id 
     * @param {DeviceType} deviceType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceTypeApiInterface
     */
    updateDeviceTypeRaw(requestParameters: UpdateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceType>>;

    /**
     */
    updateDeviceType(requestParameters: UpdateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceType>;

}

/**
 * 
 */
export class DeviceTypeApi extends runtime.BaseAPI implements DeviceTypeApiInterface {

    /**
     */
    async createDeviceTypeRaw(requestParameters: CreateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceType>> {
        if (requestParameters['deviceType'] == null) {
            throw new runtime.RequiredError(
                'deviceType',
                'Required parameter "deviceType" was null or undefined when calling createDeviceType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/deviceType`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceTypeToJSON(requestParameters['deviceType']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceTypeFromJSON(jsonValue));
    }

    /**
     */
    async createDeviceType(requestParameters: CreateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceType> {
        const response = await this.createDeviceTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteDeviceTypeRaw(requestParameters: DeleteDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDeviceType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/deviceType/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteDeviceType(requestParameters: DeleteDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDeviceTypeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getDeviceTypeRaw(requestParameters: GetDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceType>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeviceType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        const response = await this.request({
            path: `/api/v1/deviceType/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceTypeFromJSON(jsonValue));
    }

    /**
     */
    async getDeviceType(requestParameters: GetDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceType> {
        const response = await this.getDeviceTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDeviceTypesRaw(requestParameters: ListDeviceTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceTypeSearchResults>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/deviceType/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceTypeSearchBodyToJSON(requestParameters['deviceTypeSearchBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceTypeSearchResultsFromJSON(jsonValue));
    }

    /**
     */
    async listDeviceTypes(requestParameters: ListDeviceTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceTypeSearchResults> {
        const response = await this.listDeviceTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateDeviceTypeRaw(requestParameters: UpdateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceType>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateDeviceType().'
            );
        }

        if (requestParameters['deviceType'] == null) {
            throw new runtime.RequiredError(
                'deviceType',
                'Required parameter "deviceType" was null or undefined when calling updateDeviceType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/deviceType/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceTypeToJSON(requestParameters['deviceType']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceTypeFromJSON(jsonValue));
    }

    /**
     */
    async updateDeviceType(requestParameters: UpdateDeviceTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceType> {
        const response = await this.updateDeviceTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
