// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Stats,
} from '../models/index';
import {
    StatsFromJSON,
    StatsToJSON,
} from '../models/index';

/**
 * StatsApi - interface
 * 
 * @export
 * @interface StatsApiInterface
 */
export interface StatsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApiInterface
     */
    getStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stats>>;

    /**
     */
    getStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stats>;

}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI implements StatsApiInterface {

    /**
     */
    async getStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatsFromJSON(jsonValue));
    }

    /**
     */
    async getStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stats> {
        const response = await this.getStatsRaw(initOverrides);
        return await response.value();
    }

}
