// Code generated by dvnetman. DO NOT EDIT.

package openapi

type CurrentUser struct {
	DisplayName      *string `json:"displayName,omitzero"`
	Email            *string `json:"email,omitzero"`
	ExternalID       *string `json:"externalID,omitzero"`
	ExternalProvider *string `json:"externalProvider,omitzero"`
	LoggedIn         *bool   `json:"loggedIn,omitzero"`
	ProfileImageURL  *string `json:"profileImageURL,omitzero"`
}
