// Code generated by dvnetman. DO NOT EDIT.

package openapi

import (
	uuid "github.com/google/uuid"
	"time"
)

type DeviceTypeResult struct {
	Created      *time.Time       `json:"created,omitzero"`
	Id           uuid.UUID        `json:"id"`
	Manufacturer *ObjectReference `json:"manufacturer,omitzero"`
	Model        *string          `json:"model,omitzero"`
	Tags         []*Tag           `json:"tags,omitzero"`
	Updated      *time.Time       `json:"updated,omitzero"`
	Version      int              `json:"version"`
}
