// Code generated by dvnetman. DO NOT EDIT.

package openapi

type DeviceTypeSearchResults struct {
	Count int                 `json:"count"`
	Items []*DeviceTypeResult `json:"items"`
	Next  bool                `json:"next"`
}
