// Code generated by dvnetman. DO NOT EDIT.

package openapi

import uuid "github.com/google/uuid"

type DeviceTypeSearchBody struct {
	Fields       []string    `json:"fields,omitzero"`
	Ids          []uuid.UUID `json:"ids,omitzero"`
	Manufacturer []uuid.UUID `json:"manufacturer,omitzero"`
	Model        *string     `json:"model,omitzero"`
	ModelRegex   *string     `json:"modelRegex,omitzero"`
}
