// Code generated by dvnetman. DO NOT EDIT.

package openapi

import (
	"context"
	logger "dvnetman/pkg/logger"
	utils "dvnetman/pkg/utils"
	"encoding/json"
	uuid "github.com/google/uuid"
	mux "github.com/gorilla/mux"
	errors "github.com/pkg/errors"
	"net/http"
	"strconv"
	"time"
)

type DeviceTypeAPI interface {
	CreateDeviceType(ctx context.Context, opts *CreateDeviceTypeOpts) (res *Response, err error)
	DeleteDeviceType(ctx context.Context, opts *DeleteDeviceTypeOpts) (res *Response, err error)
	GetDeviceType(ctx context.Context, opts *GetDeviceTypeOpts) (res *Response, err error)
	ListDeviceTypes(ctx context.Context, opts *ListDeviceTypesOpts) (res *Response, err error)
	UpdateDeviceType(ctx context.Context, opts *UpdateDeviceTypeOpts) (res *Response, err error)
}
type CreateDeviceTypeOpts struct {
	Body *DeviceType
}
type ListDeviceTypesOpts struct {
	Page    *int
	PerPage *int
	Sort    *string
	Body    *DeviceTypeSearchBody
}
type DeleteDeviceTypeOpts struct {
	Id uuid.UUID
}
type GetDeviceTypeOpts struct {
	Id              uuid.UUID
	IfNoneMatch     *string
	IfModifiedSince *time.Time
}
type UpdateDeviceTypeOpts struct {
	Id   uuid.UUID
	Body *DeviceType
}
type DeviceTypeAPIHandler struct {
	service DeviceTypeAPI
	errors  ErrorHandler
}

func (h *DeviceTypeAPIHandler) CreateDeviceType(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &CreateDeviceTypeOpts{}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	if res, err = h.service.CreateDeviceType(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *DeviceTypeAPIHandler) ListDeviceTypes(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &ListDeviceTypesOpts{}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	for k, v := range r.URL.Query() {
		switch k {
		case "page":
			var x int
			if x, err = strconv.Atoi(v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("page", err)))
				return
			}
			opts.Page = utils.ToPtr(x)
		case "per_page":
			var x int
			if x, err = strconv.Atoi(v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("per_page", err)))
				return
			}
			opts.PerPage = utils.ToPtr(x)
		case "sort":
			opts.Sort = utils.ToPtr(v[0])
		}
	}
	if res, err = h.service.ListDeviceTypes(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *DeviceTypeAPIHandler) DeleteDeviceType(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &DeleteDeviceTypeOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	if res, err = h.service.DeleteDeviceType(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *DeviceTypeAPIHandler) GetDeviceType(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &GetDeviceTypeOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	for k, v := range r.Header {
		switch k {
		case "If-None-Match":
			opts.IfNoneMatch = utils.ToPtr(v[0])
		case "If-Modified-Since":
			var t time.Time
			if t, err = time.Parse(time.RFC1123, v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("If-Modified-Since", err)))
				return
			}
			opts.IfModifiedSince = utils.ToPtr(t)
		}
	}
	if res, err = h.service.GetDeviceType(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *DeviceTypeAPIHandler) UpdateDeviceType(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &UpdateDeviceTypeOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	if res, err = h.service.UpdateDeviceType(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func AttachDeviceTypeAPI(service DeviceTypeAPI, errors ErrorHandler, router *mux.Router) {
	handler := &DeviceTypeAPIHandler{
		errors:  errors,
		service: service,
	}
	router.Methods(http.MethodPost).Path("/api/v1/deviceType").Name("CreateDeviceType").HandlerFunc(handler.CreateDeviceType)
	router.Methods(http.MethodPost).Path("/api/v1/deviceType/search").Name("ListDeviceTypes").HandlerFunc(handler.ListDeviceTypes)
	router.Methods(http.MethodDelete).Path("/api/v1/deviceType/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("DeleteDeviceType").HandlerFunc(handler.DeleteDeviceType)
	router.Methods(http.MethodGet).Path("/api/v1/deviceType/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("GetDeviceType").HandlerFunc(handler.GetDeviceType)
	router.Methods(http.MethodPut).Path("/api/v1/deviceType/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("UpdateDeviceType").HandlerFunc(handler.UpdateDeviceType)
}
