// Code generated by dvnetman. DO NOT EDIT.

package openapi

import (
	"context"
	utils "dvnetman/pkg/utils"
	"encoding/json"
	uuid "github.com/google/uuid"
	mux "github.com/gorilla/mux"
	errors "github.com/pkg/errors"
	"net/http"
	"strconv"
	"time"
)

type DeviceAPI interface {
	CreateDevice(ctx context.Context, opts *CreateDeviceOpts) (res *Response, err error)
	DeleteDevice(ctx context.Context, opts *DeleteDeviceOpts) (res *Response, err error)
	GetDevice(ctx context.Context, opts *GetDeviceOpts) (res *Response, err error)
	ListDevices(ctx context.Context, opts *ListDevicesOpts) (res *Response, err error)
	UpdateDevice(ctx context.Context, opts *UpdateDeviceOpts) (res *Response, err error)
}
type CreateDeviceOpts struct {
	Body *Device
}
type ListDevicesOpts struct {
	Page    *int
	PerPage *int
	Sort    *string
	Body    *DeviceSearchBody
}
type DeleteDeviceOpts struct {
	Id uuid.UUID
}
type GetDeviceOpts struct {
	Id              uuid.UUID
	IfNoneMatch     *string
	IfModifiedSince *time.Time
}
type UpdateDeviceOpts struct {
	Id   uuid.UUID
	Body *Device
}
type DeviceAPIHandler struct {
	service DeviceAPI
	errors  ErrorHandler
}

func (h *DeviceAPIHandler) CreateDevice(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &CreateDeviceOpts{}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	if res, err = h.service.CreateDevice(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		h.errors.WriteErrorHandler(w, r, err)
	}
}
func (h *DeviceAPIHandler) ListDevices(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &ListDevicesOpts{}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	for k, v := range r.URL.Query() {
		switch k {
		case "page":
			var x int
			if x, err = strconv.Atoi(v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("page", err)))
				return
			}
			opts.Page = utils.ToPtr(x)
		case "per_page":
			var x int
			if x, err = strconv.Atoi(v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("per_page", err)))
				return
			}
			opts.PerPage = utils.ToPtr(x)
		case "sort":
			opts.Sort = utils.ToPtr(v[0])
		}
	}
	if res, err = h.service.ListDevices(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		h.errors.WriteErrorHandler(w, r, err)
	}
}
func (h *DeviceAPIHandler) DeleteDevice(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &DeleteDeviceOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	if res, err = h.service.DeleteDevice(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		h.errors.WriteErrorHandler(w, r, err)
	}
}
func (h *DeviceAPIHandler) GetDevice(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &GetDeviceOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	for k, v := range r.Header {
		switch k {
		case "If-None-Match":
			opts.IfNoneMatch = utils.ToPtr(v[0])
		case "If-Modified-Since":
			var t time.Time
			if t, err = time.Parse(time.RFC1123, v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("If-Modified-Since", err)))
				return
			}
			opts.IfModifiedSince = utils.ToPtr(t)
		}
	}
	if res, err = h.service.GetDevice(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		h.errors.WriteErrorHandler(w, r, err)
	}
}
func (h *DeviceAPIHandler) UpdateDevice(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &UpdateDeviceOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	if res, err = h.service.UpdateDevice(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		h.errors.WriteErrorHandler(w, r, err)
	}
}
func AttachDeviceAPI(service DeviceAPI, errors ErrorHandler, router *mux.Router) {
	handler := &DeviceAPIHandler{
		errors:  errors,
		service: service,
	}
	router.Methods(http.MethodPost).Path("/api/v1/device").Name("CreateDevice").HandlerFunc(handler.CreateDevice)
	router.Methods(http.MethodPost).Path("/api/v1/device/search").Name("ListDevices").HandlerFunc(handler.ListDevices)
	router.Methods(http.MethodDelete).Path("/api/v1/device/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("DeleteDevice").HandlerFunc(handler.DeleteDevice)
	router.Methods(http.MethodGet).Path("/api/v1/device/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("GetDevice").HandlerFunc(handler.GetDevice)
	router.Methods(http.MethodPut).Path("/api/v1/device/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("UpdateDevice").HandlerFunc(handler.UpdateDevice)
}
