// Code generated by dvnetman. DO NOT EDIT.

package openapi

import (
	uuid "github.com/google/uuid"
	"time"
)

type LocationResult struct {
	Created     *time.Time       `json:"created,omitzero"`
	Description *string          `json:"description,omitzero"`
	Id          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Parent      *ObjectReference `json:"parent,omitzero"`
	Site        *ObjectReference `json:"site,omitzero"`
	Tags        []*Tag           `json:"tags,omitzero"`
	Updated     *time.Time       `json:"updated,omitzero"`
	Version     int              `json:"version"`
}
