// Code generated by dvnetman. DO NOT EDIT.

package openapi

type LocationSearchResults struct {
	Count int               `json:"count"`
	Items []*LocationResult `json:"items"`
	Next  bool              `json:"next"`
}
