// Code generated by dvnetman. DO NOT EDIT.

package openapi

type ManufacturerSearchResults struct {
	Count int                   `json:"count"`
	Items []*ManufacturerResult `json:"items"`
	Next  bool                  `json:"next"`
}
