// Code generated by mockery v2.52.2. DO NOT EDIT.

package openapi

import mock "github.com/stretchr/testify/mock"

// MockErrorConverterFunc is an autogenerated mock type for the ErrorConverterFunc type
type MockErrorConverterFunc struct {
	mock.Mock
}

type MockErrorConverterFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorConverterFunc) EXPECT() *MockErrorConverterFunc_Expecter {
	return &MockErrorConverterFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockErrorConverterFunc) Execute(_a0 error) *Response {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *Response
	if rf, ok := ret.Get(0).(func(error) *Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	return r0
}

// MockErrorConverterFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockErrorConverterFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 error
func (_e *MockErrorConverterFunc_Expecter) Execute(_a0 interface{}) *MockErrorConverterFunc_Execute_Call {
	return &MockErrorConverterFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockErrorConverterFunc_Execute_Call) Run(run func(_a0 error)) *MockErrorConverterFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockErrorConverterFunc_Execute_Call) Return(_a0 *Response) *MockErrorConverterFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorConverterFunc_Execute_Call) RunAndReturn(run func(error) *Response) *MockErrorConverterFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockErrorConverterFunc creates a new instance of MockErrorConverterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorConverterFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorConverterFunc {
	mock := &MockErrorConverterFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
