// Code generated by dvnetman. DO NOT EDIT.

package openapi

import uuid "github.com/google/uuid"

type ObjectReference struct {
	DisplayName *string   `json:"displayName,omitzero"`
	Id          uuid.UUID `json:"id"`
}
