// Code generated by dvnetman. DO NOT EDIT.

package openapi

import (
	"context"
	logger "dvnetman/pkg/logger"
	utils "dvnetman/pkg/utils"
	"encoding/json"
	uuid "github.com/google/uuid"
	mux "github.com/gorilla/mux"
	errors "github.com/pkg/errors"
	"net/http"
	"strconv"
	"time"
)

type SiteAPI interface {
	CreateSite(ctx context.Context, opts *CreateSiteOpts) (res *Response, err error)
	DeleteSite(ctx context.Context, opts *DeleteSiteOpts) (res *Response, err error)
	GetSite(ctx context.Context, opts *GetSiteOpts) (res *Response, err error)
	ListSites(ctx context.Context, opts *ListSitesOpts) (res *Response, err error)
	UpdateSite(ctx context.Context, opts *UpdateSiteOpts) (res *Response, err error)
}
type CreateSiteOpts struct {
	Body *Site
}
type ListSitesOpts struct {
	Page    *int
	PerPage *int
	Sort    *string
	Body    *SiteSearchBody
}
type DeleteSiteOpts struct {
	Id uuid.UUID
}
type GetSiteOpts struct {
	Id              uuid.UUID
	IfNoneMatch     *string
	IfModifiedSince *time.Time
}
type UpdateSiteOpts struct {
	Id   uuid.UUID
	Body *Site
}
type SiteAPIHandler struct {
	service SiteAPI
	errors  ErrorHandler
}

func (h *SiteAPIHandler) CreateSite(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &CreateSiteOpts{}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	if res, err = h.service.CreateSite(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *SiteAPIHandler) ListSites(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &ListSitesOpts{}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	for k, v := range r.URL.Query() {
		switch k {
		case "page":
			var x int
			if x, err = strconv.Atoi(v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("page", err)))
				return
			}
			opts.Page = utils.ToPtr(x)
		case "per_page":
			var x int
			if x, err = strconv.Atoi(v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("per_page", err)))
				return
			}
			opts.PerPage = utils.ToPtr(x)
		case "sort":
			opts.Sort = utils.ToPtr(v[0])
		}
	}
	if res, err = h.service.ListSites(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *SiteAPIHandler) DeleteSite(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &DeleteSiteOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	if res, err = h.service.DeleteSite(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *SiteAPIHandler) GetSite(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &GetSiteOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	for k, v := range r.Header {
		switch k {
		case "If-None-Match":
			opts.IfNoneMatch = utils.ToPtr(v[0])
		case "If-Modified-Since":
			var t time.Time
			if t, err = time.Parse(time.RFC1123, v[0]); err != nil {
				h.errors.ErrorHandler(w, r, errors.WithStack(NewQueryParamError("If-Modified-Since", err)))
				return
			}
			opts.IfModifiedSince = utils.ToPtr(t)
		}
	}
	if res, err = h.service.GetSite(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func (h *SiteAPIHandler) UpdateSite(w http.ResponseWriter, r *http.Request) {
	var res *Response
	var err error
	opts := &UpdateSiteOpts{}
	vars := mux.Vars(r)
	if opts.Id, err = uuid.Parse(vars["id"]); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewPathParamError("Id", err)))
		return
	}
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err = decoder.Decode(&opts.Body); err != nil {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(err)))
		return
	}
	if decoder.More() {
		h.errors.ErrorHandler(w, r, errors.WithStack(NewBodyParamError(errors.New("unexpected data after body"))))
		return
	}
	if res, err = h.service.UpdateSite(r.Context(), opts); err != nil {
		h.errors.ErrorHandler(w, r, err)
	} else if res == nil {
		h.errors.ErrorHandler(w, r, errors.Errorf("no response returned"))
	} else if err = res.Write(r, w); err != nil {
		logger.Info(r.Context()).Err(err).Msg("error writing response")
	}
}
func AttachSiteAPI(service SiteAPI, errors ErrorHandler, router *mux.Router) {
	handler := &SiteAPIHandler{
		errors:  errors,
		service: service,
	}
	router.Methods(http.MethodPost).Path("/api/v1/site").Name("CreateSite").HandlerFunc(handler.CreateSite)
	router.Methods(http.MethodPost).Path("/api/v1/site/search").Name("ListSites").HandlerFunc(handler.ListSites)
	router.Methods(http.MethodDelete).Path("/api/v1/site/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("DeleteSite").HandlerFunc(handler.DeleteSite)
	router.Methods(http.MethodGet).Path("/api/v1/site/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("GetSite").HandlerFunc(handler.GetSite)
	router.Methods(http.MethodPut).Path("/api/v1/site/{id:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}}").Name("UpdateSite").HandlerFunc(handler.UpdateSite)
}
