// Code generated by dvnetman. DO NOT EDIT.

package openapi

type SiteSearchResults struct {
	Count int           `json:"count"`
	Items []*SiteResult `json:"items"`
	Next  bool          `json:"next"`
}
