// Code generated by dvnetman. DO NOT EDIT.

package openapi

type Stats struct {
	DeviceCount     *int `json:"deviceCount,omitzero"`
	DeviceTypeCount *int `json:"deviceTypeCount,omitzero"`
	UserCount       *int `json:"userCount,omitzero"`
}
