// Code generated by dvnetman. DO NOT EDIT.

package openapi

type Stats struct {
	DeviceCount       int `json:"deviceCount"`
	DeviceTypeCount   int `json:"deviceTypeCount"`
	LocationCount     int `json:"locationCount"`
	ManufacturerCount int `json:"manufacturerCount"`
	SiteCount         int `json:"siteCount"`
	UserCount         int `json:"userCount"`
}
