// Code generated by dvnetman. DO NOT EDIT.

package openapi

type Stats struct {
	DeviceCount       int `json:"deviceCount"`
	DeviceTypeCount   int `json:"deviceTypeCount"`
	ManufacturerCount int `json:"manufacturerCount"`
	UserCount         int `json:"userCount"`
}
