// Code generated by dvnetman. DO NOT EDIT.

package openapi

import uuid "github.com/google/uuid"

type UserResult struct {
	Email     *string   `json:"email,omitzero"`
	FirstName *string   `json:"firstName,omitzero"`
	Id        uuid.UUID `json:"id"`
	LastName  *string   `json:"lastName,omitzero"`
}
