// Code generated by dvnetman. DO NOT EDIT.

package openapi

import uuid "github.com/google/uuid"

type UserSearchBody struct {
	DisplayName      *string     `json:"displayName,omitzero"`
	DisplayNameRegex *string     `json:"displayNameRegex,omitzero"`
	Email            *string     `json:"email,omitzero"`
	Fields           []string    `json:"fields,omitzero"`
	FirstName        *string     `json:"firstName,omitzero"`
	FirstNameRegex   *string     `json:"firstNameRegex,omitzero"`
	Ids              []uuid.UUID `json:"ids,omitzero"`
	LastName         *string     `json:"lastName,omitzero"`
	LastNameRegex    *string     `json:"lastNameRegex,omitzero"`
}
