// Code generated by dvnetman. DO NOT EDIT.

package openapi

import (
	uuid "github.com/google/uuid"
	"time"
)

type User struct {
	Created          *time.Time `json:"created,omitzero"`
	Email            *string    `json:"email,omitzero"`
	ExternalID       *string    `json:"externalID,omitzero"`
	ExternalProvider *string    `json:"externalProvider,omitzero"`
	FirstName        *string    `json:"firstName,omitzero"`
	Id               uuid.UUID  `json:"id"`
	LastName         *string    `json:"lastName,omitzero"`
	Password         *string    `json:"password,omitzero"`
	Tags             []*Tag     `json:"tags,omitzero"`
	Updated          *time.Time `json:"updated,omitzero"`
	Version          int        `json:"version"`
}
