// Code generated by dvnetman. DO NOT EDIT.

package openapi

import uuid "github.com/google/uuid"

type UserSearchBody struct {
	Email          *string     `json:"email,omitzero"`
	Fields         []string    `json:"fields,omitzero"`
	FirstName      *string     `json:"firstName,omitzero"`
	FirstNameRegex *string     `json:"firstNameRegex,omitzero"`
	FullName       *string     `json:"fullName,omitzero"`
	FullNameRegex  *string     `json:"fullNameRegex,omitzero"`
	Ids            []uuid.UUID `json:"ids,omitzero"`
	LastName       *string     `json:"lastName,omitzero"`
	LastNameRegex  *string     `json:"lastNameRegex,omitzero"`
	Username       *string     `json:"username,omitzero"`
	UsernameRegex  *string     `json:"usernameRegex,omitzero"`
}
