// Code generated by dvnetman. DO NOT EDIT.

package openapi

type UserProvider struct {
	DisplayName         string  `json:"displayName"`
	LoginButtonImageURL *string `json:"loginButtonImageURL,omitzero"`
	LoginURL            string  `json:"loginURL"`
	Provider            string  `json:"provider"`
}
