// Code generated by dvnetman. DO NOT EDIT.

package openapi

import uuid "github.com/google/uuid"

type UserResult struct {
	DisplayName *string    `json:"displayName,omitzero"`
	Id          *uuid.UUID `json:"id,omitzero"`
}
