// Code generated by dvnetman. DO NOT EDIT.

package openapi

type UserSearchResults struct {
	Count int           `json:"count"`
	Items []*UserResult `json:"items"`
	Next  bool          `json:"next"`
}
