// Code generated by mockery v2.52.2. DO NOT EDIT.

package mongoadapt

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMongoCursor is an autogenerated mock type for the MongoCursor type
type MockMongoCursor struct {
	mock.Mock
}

type MockMongoCursor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoCursor) EXPECT() *MockMongoCursor_Expecter {
	return &MockMongoCursor_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: ctx, result
func (_m *MockMongoCursor) All(ctx context.Context, result interface{}) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMongoCursor_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockMongoCursor_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - result interface{}
func (_e *MockMongoCursor_Expecter) All(ctx interface{}, result interface{}) *MockMongoCursor_All_Call {
	return &MockMongoCursor_All_Call{Call: _e.mock.On("All", ctx, result)}
}

func (_c *MockMongoCursor_All_Call) Run(run func(ctx context.Context, result interface{})) *MockMongoCursor_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockMongoCursor_All_Call) Return(_a0 error) *MockMongoCursor_All_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoCursor_All_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockMongoCursor_All_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *MockMongoCursor) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMongoCursor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMongoCursor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoCursor_Expecter) Close(ctx interface{}) *MockMongoCursor_Close_Call {
	return &MockMongoCursor_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockMongoCursor_Close_Call) Run(run func(ctx context.Context)) *MockMongoCursor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMongoCursor_Close_Call) Return(_a0 error) *MockMongoCursor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoCursor_Close_Call) RunAndReturn(run func(context.Context) error) *MockMongoCursor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function with given fields: v
func (_m *MockMongoCursor) Decode(v interface{}) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMongoCursor_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockMongoCursor_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - v interface{}
func (_e *MockMongoCursor_Expecter) Decode(v interface{}) *MockMongoCursor_Decode_Call {
	return &MockMongoCursor_Decode_Call{Call: _e.mock.On("Decode", v)}
}

func (_c *MockMongoCursor_Decode_Call) Run(run func(v interface{})) *MockMongoCursor_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockMongoCursor_Decode_Call) Return(_a0 error) *MockMongoCursor_Decode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoCursor_Decode_Call) RunAndReturn(run func(interface{}) error) *MockMongoCursor_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with given fields: ctx
func (_m *MockMongoCursor) Next(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMongoCursor_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockMongoCursor_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoCursor_Expecter) Next(ctx interface{}) *MockMongoCursor_Next_Call {
	return &MockMongoCursor_Next_Call{Call: _e.mock.On("Next", ctx)}
}

func (_c *MockMongoCursor_Next_Call) Run(run func(ctx context.Context)) *MockMongoCursor_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMongoCursor_Next_Call) Return(_a0 bool) *MockMongoCursor_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoCursor_Next_Call) RunAndReturn(run func(context.Context) bool) *MockMongoCursor_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMongoCursor creates a new instance of MockMongoCursor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoCursor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoCursor {
	mock := &MockMongoCursor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
