// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface APIError
 */
export interface APIError {
    /**
     * 
     * @type {Array<ErrorMessage>}
     * @memberof APIError
     */
    errors?: Array<ErrorMessage>;
}

/**
 * Check if a given object implements the APIError interface.
 */
export function instanceOfAPIError(value: object): value is APIError {
    return true;
}

export function APIErrorFromJSON(json: any): APIError {
    return APIErrorFromJSONTyped(json, false);
}

export function APIErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIError {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ErrorMessageFromJSON)),
    };
}

export function APIErrorToJSON(json: any): APIError {
    return APIErrorToJSONTyped(json, false);
}

export function APIErrorToJSONTyped(value?: APIError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ErrorMessageToJSON)),
    };
}

