// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentUser
 */
export interface CurrentUser {
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    externalID?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    externalProvider?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CurrentUser
     */
    loggedIn?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    profileImageURL?: string;
}

/**
 * Check if a given object implements the CurrentUser interface.
 */
export function instanceOfCurrentUser(value: object): value is CurrentUser {
    return true;
}

export function CurrentUserFromJSON(json: any): CurrentUser {
    return CurrentUserFromJSONTyped(json, false);
}

export function CurrentUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUser {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
        'externalID': json['externalID'] == null ? undefined : json['externalID'],
        'externalProvider': json['externalProvider'] == null ? undefined : json['externalProvider'],
        'loggedIn': json['loggedIn'] == null ? undefined : json['loggedIn'],
        'profileImageURL': json['profileImageURL'] == null ? undefined : json['profileImageURL'],
    };
}

export function CurrentUserToJSON(json: any): CurrentUser {
    return CurrentUserToJSONTyped(json, false);
}

export function CurrentUserToJSONTyped(value?: CurrentUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'email': value['email'],
        'externalID': value['externalID'],
        'externalProvider': value['externalProvider'],
        'loggedIn': value['loggedIn'],
        'profileImageURL': value['profileImageURL'],
    };
}

