// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DevicePort
 */
export interface DevicePort {
    /**
     * 
     * @type {string}
     * @memberof DevicePort
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof DevicePort
     */
    name?: string;
}

/**
 * Check if a given object implements the DevicePort interface.
 */
export function instanceOfDevicePort(value: object): value is DevicePort {
    return true;
}

export function DevicePortFromJSON(json: any): DevicePort {
    return DevicePortFromJSONTyped(json, false);
}

export function DevicePortFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevicePort {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DevicePortToJSON(json: any): DevicePort {
    return DevicePortToJSONTyped(json, false);
}

export function DevicePortToJSONTyped(value?: Omit<DevicePort, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

