// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectReference } from './ObjectReference';
import {
    ObjectReferenceFromJSON,
    ObjectReferenceFromJSONTyped,
    ObjectReferenceToJSON,
    ObjectReferenceToJSONTyped,
} from './ObjectReference';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * 
 * @export
 * @interface DeviceTypeResult
 */
export interface DeviceTypeResult {
    /**
     * 
     * @type {Date}
     * @memberof DeviceTypeResult
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof DeviceTypeResult
     */
    readonly id?: string;
    /**
     * 
     * @type {ObjectReference}
     * @memberof DeviceTypeResult
     */
    manufacturer?: ObjectReference;
    /**
     * 
     * @type {string}
     * @memberof DeviceTypeResult
     */
    model?: string;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof DeviceTypeResult
     */
    tags?: Array<Tag>;
    /**
     * 
     * @type {Date}
     * @memberof DeviceTypeResult
     */
    updated?: Date;
    /**
     * 
     * @type {number}
     * @memberof DeviceTypeResult
     */
    version: number;
}

/**
 * Check if a given object implements the DeviceTypeResult interface.
 */
export function instanceOfDeviceTypeResult(value: object): value is DeviceTypeResult {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function DeviceTypeResultFromJSON(json: any): DeviceTypeResult {
    return DeviceTypeResultFromJSONTyped(json, false);
}

export function DeviceTypeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceTypeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'id': json['id'] == null ? undefined : json['id'],
        'manufacturer': json['manufacturer'] == null ? undefined : ObjectReferenceFromJSON(json['manufacturer']),
        'model': json['model'] == null ? undefined : json['model'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'version': json['version'],
    };
}

export function DeviceTypeResultToJSON(json: any): DeviceTypeResult {
    return DeviceTypeResultToJSONTyped(json, false);
}

export function DeviceTypeResultToJSONTyped(value?: Omit<DeviceTypeResult, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'manufacturer': ObjectReferenceToJSON(value['manufacturer']),
        'model': value['model'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
        'updated': value['updated'] == null ? undefined : ((value['updated']).toISOString()),
        'version': value['version'],
    };
}

