// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectReference } from './ObjectReference';
import {
    ObjectReferenceFromJSON,
    ObjectReferenceFromJSONTyped,
    ObjectReferenceToJSON,
    ObjectReferenceToJSONTyped,
} from './ObjectReference';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * 
 * @export
 * @interface DeviceType
 */
export interface DeviceType {
    /**
     * 
     * @type {Date}
     * @memberof DeviceType
     */
    readonly created?: Date;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    readonly id: string;
    /**
     * 
     * @type {ObjectReference}
     * @memberof DeviceType
     */
    manufacturer?: ObjectReference;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    model?: string;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof DeviceType
     */
    tags?: Array<Tag>;
    /**
     * 
     * @type {Date}
     * @memberof DeviceType
     */
    readonly updated?: Date;
    /**
     * 
     * @type {number}
     * @memberof DeviceType
     */
    version: number;
}

/**
 * Check if a given object implements the DeviceType interface.
 */
export function instanceOfDeviceType(value: object): value is DeviceType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function DeviceTypeFromJSON(json: any): DeviceType {
    return DeviceTypeFromJSONTyped(json, false);
}

export function DeviceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceType {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'id': json['id'],
        'manufacturer': json['manufacturer'] == null ? undefined : ObjectReferenceFromJSON(json['manufacturer']),
        'model': json['model'] == null ? undefined : json['model'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'version': json['version'],
    };
}

export function DeviceTypeToJSON(json: any): DeviceType {
    return DeviceTypeToJSONTyped(json, false);
}

export function DeviceTypeToJSONTyped(value?: Omit<DeviceType, 'created'|'id'|'updated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'manufacturer': ObjectReferenceToJSON(value['manufacturer']),
        'model': value['model'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
        'version': value['version'],
    };
}

