// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocationResult } from './LocationResult';
import {
    LocationResultFromJSON,
    LocationResultFromJSONTyped,
    LocationResultToJSON,
    LocationResultToJSONTyped,
} from './LocationResult';

/**
 * 
 * @export
 * @interface LocationSearchResults
 */
export interface LocationSearchResults {
    /**
     * 
     * @type {number}
     * @memberof LocationSearchResults
     */
    count: number;
    /**
     * 
     * @type {Array<LocationResult>}
     * @memberof LocationSearchResults
     */
    items: Array<LocationResult>;
    /**
     * 
     * @type {boolean}
     * @memberof LocationSearchResults
     */
    next: boolean;
}

/**
 * Check if a given object implements the LocationSearchResults interface.
 */
export function instanceOfLocationSearchResults(value: object): value is LocationSearchResults {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    return true;
}

export function LocationSearchResultsFromJSON(json: any): LocationSearchResults {
    return LocationSearchResultsFromJSONTyped(json, false);
}

export function LocationSearchResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationSearchResults {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'items': ((json['items'] as Array<any>).map(LocationResultFromJSON)),
        'next': json['next'],
    };
}

export function LocationSearchResultsToJSON(json: any): LocationSearchResults {
    return LocationSearchResultsToJSONTyped(json, false);
}

export function LocationSearchResultsToJSONTyped(value?: LocationSearchResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'items': ((value['items'] as Array<any>).map(LocationResultToJSON)),
        'next': value['next'],
    };
}

