// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ManufacturerResult } from './ManufacturerResult';
import {
    ManufacturerResultFromJSON,
    ManufacturerResultFromJSONTyped,
    ManufacturerResultToJSON,
    ManufacturerResultToJSONTyped,
} from './ManufacturerResult';

/**
 * 
 * @export
 * @interface ManufacturerSearchResults
 */
export interface ManufacturerSearchResults {
    /**
     * 
     * @type {number}
     * @memberof ManufacturerSearchResults
     */
    count: number;
    /**
     * 
     * @type {Array<ManufacturerResult>}
     * @memberof ManufacturerSearchResults
     */
    items: Array<ManufacturerResult>;
    /**
     * 
     * @type {boolean}
     * @memberof ManufacturerSearchResults
     */
    next: boolean;
}

/**
 * Check if a given object implements the ManufacturerSearchResults interface.
 */
export function instanceOfManufacturerSearchResults(value: object): value is ManufacturerSearchResults {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    return true;
}

export function ManufacturerSearchResultsFromJSON(json: any): ManufacturerSearchResults {
    return ManufacturerSearchResultsFromJSONTyped(json, false);
}

export function ManufacturerSearchResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManufacturerSearchResults {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'items': ((json['items'] as Array<any>).map(ManufacturerResultFromJSON)),
        'next': json['next'],
    };
}

export function ManufacturerSearchResultsToJSON(json: any): ManufacturerSearchResults {
    return ManufacturerSearchResultsToJSONTyped(json, false);
}

export function ManufacturerSearchResultsToJSONTyped(value?: ManufacturerSearchResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'items': ((value['items'] as Array<any>).map(ManufacturerResultToJSON)),
        'next': value['next'],
    };
}

