// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManufacturerSearchBody
 */
export interface ManufacturerSearchBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof ManufacturerSearchBody
     */
    fields?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ManufacturerSearchBody
     */
    ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ManufacturerSearchBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ManufacturerSearchBody
     */
    nameRegex?: string;
}

/**
 * Check if a given object implements the ManufacturerSearchBody interface.
 */
export function instanceOfManufacturerSearchBody(value: object): value is ManufacturerSearchBody {
    return true;
}

export function ManufacturerSearchBodyFromJSON(json: any): ManufacturerSearchBody {
    return ManufacturerSearchBodyFromJSONTyped(json, false);
}

export function ManufacturerSearchBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManufacturerSearchBody {
    if (json == null) {
        return json;
    }
    return {
        
        'fields': json['fields'] == null ? undefined : json['fields'],
        'ids': json['ids'] == null ? undefined : json['ids'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameRegex': json['nameRegex'] == null ? undefined : json['nameRegex'],
    };
}

export function ManufacturerSearchBodyToJSON(json: any): ManufacturerSearchBody {
    return ManufacturerSearchBodyToJSONTyped(json, false);
}

export function ManufacturerSearchBodyToJSONTyped(value?: ManufacturerSearchBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fields': value['fields'],
        'ids': value['ids'],
        'name': value['name'],
        'nameRegex': value['nameRegex'],
    };
}

