// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * 
 * @export
 * @interface ManufacturerResult
 */
export interface ManufacturerResult {
    /**
     * 
     * @type {Date}
     * @memberof ManufacturerResult
     */
    readonly created?: Date;
    /**
     * 
     * @type {string}
     * @memberof ManufacturerResult
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof ManufacturerResult
     */
    name: string;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof ManufacturerResult
     */
    tags?: Array<Tag>;
    /**
     * 
     * @type {Date}
     * @memberof ManufacturerResult
     */
    readonly updated?: Date;
    /**
     * 
     * @type {number}
     * @memberof ManufacturerResult
     */
    version: number;
}

/**
 * Check if a given object implements the ManufacturerResult interface.
 */
export function instanceOfManufacturerResult(value: object): value is ManufacturerResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ManufacturerResultFromJSON(json: any): ManufacturerResult {
    return ManufacturerResultFromJSONTyped(json, false);
}

export function ManufacturerResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManufacturerResult {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'id': json['id'],
        'name': json['name'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'version': json['version'],
    };
}

export function ManufacturerResultToJSON(json: any): ManufacturerResult {
    return ManufacturerResultToJSONTyped(json, false);
}

export function ManufacturerResultToJSONTyped(value?: Omit<ManufacturerResult, 'created'|'id'|'updated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
        'version': value['version'],
    };
}

