// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectReference
 */
export interface ObjectReference {
    /**
     * 
     * @type {string}
     * @memberof ObjectReference
     */
    readonly displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectReference
     */
    id: string;
}

/**
 * Check if a given object implements the ObjectReference interface.
 */
export function instanceOfObjectReference(value: object): value is ObjectReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ObjectReferenceFromJSON(json: any): ObjectReference {
    return ObjectReferenceFromJSONTyped(json, false);
}

export function ObjectReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectReference {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'id': json['id'],
    };
}

export function ObjectReferenceToJSON(json: any): ObjectReference {
    return ObjectReferenceToJSONTyped(json, false);
}

export function ObjectReferenceToJSONTyped(value?: Omit<ObjectReference, 'displayName'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

