// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteSearchBody
 */
export interface SiteSearchBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof SiteSearchBody
     */
    fields?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SiteSearchBody
     */
    ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SiteSearchBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SiteSearchBody
     */
    nameRegex?: string;
}

/**
 * Check if a given object implements the SiteSearchBody interface.
 */
export function instanceOfSiteSearchBody(value: object): value is SiteSearchBody {
    return true;
}

export function SiteSearchBodyFromJSON(json: any): SiteSearchBody {
    return SiteSearchBodyFromJSONTyped(json, false);
}

export function SiteSearchBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteSearchBody {
    if (json == null) {
        return json;
    }
    return {
        
        'fields': json['fields'] == null ? undefined : json['fields'],
        'ids': json['ids'] == null ? undefined : json['ids'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameRegex': json['nameRegex'] == null ? undefined : json['nameRegex'],
    };
}

export function SiteSearchBodyToJSON(json: any): SiteSearchBody {
    return SiteSearchBodyToJSONTyped(json, false);
}

export function SiteSearchBodyToJSONTyped(value?: SiteSearchBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fields': value['fields'],
        'ids': value['ids'],
        'name': value['name'],
        'nameRegex': value['nameRegex'],
    };
}

