// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResult
 */
export interface UserResult {
    /**
     * 
     * @type {string}
     * @memberof UserResult
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResult
     */
    id?: string;
}

/**
 * Check if a given object implements the UserResult interface.
 */
export function instanceOfUserResult(value: object): value is UserResult {
    return true;
}

export function UserResultFromJSON(json: any): UserResult {
    return UserResultFromJSONTyped(json, false);
}

export function UserResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResult {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UserResultToJSON(json: any): UserResult {
    return UserResultToJSONTyped(json, false);
}

export function UserResultToJSONTyped(value?: UserResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'id': value['id'],
    };
}

