// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserResult
 */
export interface UserResult {
  /**
   *
   * @type {string}
   * @memberof UserResult
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof UserResult
   */
  firstName?: string
  /**
   *
   * @type {string}
   * @memberof UserResult
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof UserResult
   */
  lastName?: string
  /**
   *
   * @type {string}
   * @memberof UserResult
   */
  username?: string
}

/**
 * Check if a given object implements the UserResult interface.
 */
export function instanceOfUserResult(value: object): value is UserResult {
  if (!('id' in value) || value['id'] === undefined) return false
    return true;
}

export function UserResultFromJSON(json: any): UserResult {
    return UserResultFromJSONTyped(json, false);
}

export function UserResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResult {
    if (json == null) {
        return json;
    }
    return {
      email: json['email'] == null ? undefined : json['email'],
      firstName: json['firstName'] == null ? undefined : json['firstName'],
      id: json['id'],
      lastName: json['lastName'] == null ? undefined : json['lastName'],
      username: json['username'] == null ? undefined : json['username'],
    }
}

export function UserResultToJSON(json: any): UserResult {
    return UserResultToJSONTyped(json, false);
}

export function UserResultToJSONTyped(value?: UserResult | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    email: value['email'],
    firstName: value['firstName'],
    id: value['id'],
    lastName: value['lastName'],
    username: value['username'],
  }
}

