// noinspection all
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DVNetMan
 * DVNetMan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProvider
 */
export interface UserProvider {
    /**
     * 
     * @type {string}
     * @memberof UserProvider
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof UserProvider
     */
    loginButtonImageURL?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProvider
     */
    loginURL: string;
    /**
     * 
     * @type {string}
     * @memberof UserProvider
     */
    provider: string;
}

/**
 * Check if a given object implements the UserProvider interface.
 */
export function instanceOfUserProvider(value: object): value is UserProvider {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('loginURL' in value) || value['loginURL'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function UserProviderFromJSON(json: any): UserProvider {
    return UserProviderFromJSONTyped(json, false);
}

export function UserProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'],
        'loginButtonImageURL': json['loginButtonImageURL'] == null ? undefined : json['loginButtonImageURL'],
        'loginURL': json['loginURL'],
        'provider': json['provider'],
    };
}

export function UserProviderToJSON(json: any): UserProvider {
    return UserProviderToJSONTyped(json, false);
}

export function UserProviderToJSONTyped(value?: UserProvider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'loginButtonImageURL': value['loginButtonImageURL'],
        'loginURL': value['loginURL'],
        'provider': value['provider'],
    };
}

